FROM python:3.14-alpine

WORKDIR /app

# Устанавливаем необходимые библиотеки
RUN pip install --no-cache-dir requests

RUN pip install aiohttp

COPY weather_service.py .

EXPOSE 8002

CMD ["python", "weather_service.py"]