FROM python:3.14-alpine

WORKDIR /app

# Установка зависимостей
RUN pip install --no-cache-dir httpx dadata

# Устанавливаем необходимые библиотеки
RUN pip install --no-cache-dir requests

RUN pip install aiohttp

COPY ip_service.py .

EXPOSE 8001

CMD ["python", "ip_service.py"]